apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auditor
spec:
  schedule: "25 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: auditor
            image: bitmuglemining/services:latest
            #command: ["sleep", "999"]
            command: ["/usr/local/bin/auditor.py"]
            env:
            - name: WALLET_OWNER_API_USER
              valueFrom:
                secretKeyRef:
                  name: wallet-owner-api
                  key: username.txt
            - name: WALLET_OWNER_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallet-owner-api
                  key: password.txt
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          restartPolicy: Never
          imagePullSecrets:
          - name: regsecret
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
