apiVersion: v1
kind: Service
metadata:
  name: muglewallet
  labels:
    run: muglewallet
spec:
  type: NodePort
  ports:
  - port: 13415
    nodePort: 30415
    protocol: TCP
    name: public
  - port: 13420
    protocol: TCP
    name: private
  - port: 13425
    protocol: TCP
    name: api
  selector:
    run: muglewallet
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: muglewallet
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: muglewallet
    spec:
      hostname: "muglewallet"
      containers:
      - name: public
        image: bitmuglemining/bitmugle:latest
        args: ["/run-wallet.sh", "public"]
        #args: ["sleep", "9999999"]
        env:
        - name: DEBUG_HOLD
          value:
        - name: WALLET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: muglewallet
              key: password.txt
        ports:
        - containerPort: 13415
        volumeMounts: # directory inside container
        - mountPath: /wallet
          name: muglewallet
      - name: private
        image: bitmuglemining/bitmugle:latest
        #command: ["sleep", "9999999999"]
        command: ["/run-wallet.sh", "private"]
        env:
        - name: KEYBASE_ALLOW_ROOT
          value: "1"
        - name: WALLET_OWNER_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wallet-owner-api
              key: password.txt
        - name: WALLET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: muglewallet
              key: password.txt
        ports:
        - containerPort: 13420
        volumeMounts: # directory inside container
        - mountPath: /wallet
          name: muglewallet
        - mountPath: /keybase
          name: keybase
      - name: api
        image: bitmuglemining/services:latest
        #command: ["sleep", "9999999999"]
        command: ["/usr/local/bin/api/payment_api.py"]
        env:
        - name: WALLET_OWNER_API_USER
          valueFrom:
            secretKeyRef:
              name: wallet-owner-api
              key: username.txt
        - name: WALLET_OWNER_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wallet-owner-api
              key: password.txt
        - name: MUGLE_POOL_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: muglepool-admin
              key: username.txt
        - name: MUGLE_POOL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: muglepool-admin
              key: password.txt
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 13425
#      - name: keybase
#        image: bitmuglemining/keybase:latest
#        #command: ["/entrypoint.sh"]
#        command: ["sleep", "9909999"]
#        env:
#        - name: MYDOMAIN
#          value: "bitmuglemining.com"
#        - name: AUTH_SA
#          valueFrom:
#            secretKeyRef:
#              name: storage-update
#              key: muglepool-serviceaccount-storage-update.json
#        ports:
#        - containerPort: 13415
#        volumeMounts: # directory inside container
#        - mountPath: /keybase
#          name: keybase
      volumes:
      - name: muglewallet
        persistentVolumeClaim:
          claimName: muglewallet
      - name: keybase
        emptyDir: {}
