apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: poolblockunlocker
spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: blockunlocker
            image: bitmuglemining/services:latest
            command: ["/usr/local/bin/poolblockUnlocker.py"]
            env:
            - name: WALLET_OWNER_API_USER
              valueFrom:
                secretKeyRef:
                  name: wallet-owner-api
                  key: username.txt
            - name: WALLET_OWNER_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wallet-owner-api
                  key: password.txt
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          restartPolicy: Never
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
