---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rmqdata
  labels:
    node: lucy
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/rmq
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lucy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmqdata
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      node: lucy
