apiVersion: v1
kind: Service
metadata:
  name: stratumx
  labels:
    run: stratumx
spec:
  type: LoadBalancer
  loadBalancerIP: 34.76.49.235
  ports:
  - port: 3333
    name: stratumx
    protocol: TCP
  selector:
    run: stratumx
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stratumx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stratumx
    spec:
      containers:
      - name: stratumx
        image: bitmuglemining/stratumx:latest
        command: ["/run.sh"]
        ports:
        - containerPort: 3333
        volumeMounts:
        - name: logdir
          mountPath: /stratum
      - name: sharewatcher
        image: bitmuglemining/logstash:latest
        command: ["/run.sh", "poolsharefilter.conf"]
        env:
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: rmq
              key: username.txt
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmq
              key: password.txt
        volumeMounts:
        - name: logdir
          mountPath: /stratum
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: logdir
        emptyDir: {}

