apiVersion: v1
kind: Service
metadata:
  name: stratum-md
  labels:
    run: stratum-md
spec:
  type: LoadBalancer
  loadBalancerIP: 34.76.143.174
  ports:
  - port: 3333
    name: stratum-md
    protocol: TCP
  selector:
    run: stratum-md
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stratum-md
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: stratum-md
    spec:
      containers:
      - name: stratum-md
        image: bitmuglemining/stratum:latest
        command: ["/run.sh"]
        env:
        - name: DIFFICULTY
          value: "64"
        - name: MUGLE_ADDRESS
          value: "mugle"
        - name: POOL
          valueFrom:
            configMapKeyRef:
              name: environment
              key: pool
        ports:
        - containerPort: 3333
        volumeMounts:
        - name: logdir
          mountPath: /stratum
        resources:
          requests:
            cpu: 10m
      - name: sharewatcher
        image: bitmuglemining/logstash:latest
        command: ["/run.sh", "sharefilter.conf"]
        env:
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: rmq
              key: username.txt
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmq
              key: password.txt
        volumeMounts:
        - name: logdir
          mountPath: /stratum
        resources:
          requests:
            cpu: 10m
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: logdir
        emptyDir: {}

